### ISSUE TITLE
Properties cannot be accessed on AppLocalizations because potentially null

### ISSUE THREAD

**Issue by ftaebi** [BenjaminCanape/RunFlutterRun#20]
Hi, first of all: thanks for sharing your project. I just checked out the newest version and tried to run it.
Unfortunately I get a lot of errors, all regarding gen_l10n. They are all of the form

lib/presentation/activity_list/screen/activity_list_screen.dart:27:52: Error: Property 'activity_list' cannot be accessed on 'AppLocalizations?' because it is potentially null.
 - 'AppLocalizations' is from 'package:flutter_gen/gen_l10n/app_localizations.dart' ('.dart_tool/flutter_gen/gen_l10n/app_localizations.dart').
Try accessing using ?. instead.
                      AppLocalizations.of(context).activity_list,

My system:
Flutter 3.13.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2f708eb839 (8 days ago) • 2023-10-09 09:58:08 -0500
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

Dart SDK version: 3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "linux_x64"

What can I do to resolve this?
Thanks

**Comment by BenjaminCanape** [comment]
Hello, 

First of all, thank you for the interest for this project.

I'll try to fix this. I see that in the flutter documentation:
https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization

when using AppLocalizations.of(context)!.hello('John')
there the '!' character to force the value to not be null.

I removed it because in VS Code I have this message:
The '!' will have no effect because the receiver can't be null.
Try removing the '!' operator.

But I will try to add them back again and push it to the main branch as soon as I finished.

Thank you

**Comment by BenjaminCanape** [comment]
I just merged a fix. Can you please try again and tell me if it solve the problem ?

**Comment by ftaebi** [comment]
Thank you Benjamin, I'll check it as soon as possible.On Oct 17, 2023 11:03 PM, Benjamin Canape ***@***.***> wrote:
I just merged a fix. Can you please try again and tell me if it solve the problem ?

**Comment by ftaebi** [comment]
I just checked again and the issue is resolved. Thank you

**Comment by BenjaminCanape** [comment]
That's great. You're welcome.
